[package]
name = "tera-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.5.0"
serde_json = "1.0.81"
tera = { version = "1.15.0", default-features = false }
