"""empty message

Revision ID: ff0b9f0c8a09
Revises: 86616c01ac16
Create Date: 2020-01-04 14:20:58.834297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0b9f0c8a09'
down_revision = '86616c01ac16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('surveys', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'creator_id')
    op.drop_table('users')
    # ### end Alembic commands ###
