name: Deploy
on:
    # 每当 push 到 main 分支时触发部署
    push:
        branches: [main]

jobs:
    pages:
        name: GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Install Rust (rustup)
              run: rustup update stable --no-self-update && rustup default stable

            - name: Install mdbook
              run: cargo install mdbook

            - name: Build book
              run: mdbook build

            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  # 部署到 gh-pages 分支
                  target_branch: gh-pages
                  # 部署目录为 book
                  build_dir: book
              env:
                  GITHUB_TOKEN: ${{ secrets.PAGES_GENERATE_TOKEN }}
