name: Deploy
on:
    # 每当 push 到 main 分支时触发部署
    push:
        branches: [main]

jobs:
    pages:
        name: GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install Rust (rustup)
              run: rustup update stable --no-self-update && rustup default stable
            - name: Build book
              run: cargo run -- build guide
            - name: Deploy to GitHub
              env:
                  GITHUB_DEPLOY_KEY: ${{ secrets.PAGES_GENERATE_TOKEN }}
              run: |
                  touch book/.nojekyll
                  curl -LsSf https://raw.githubusercontent.com/rust-lang/simpleinfra/master/setup-deploy-keys/src/deploy.rs | rustc - -o /tmp/deploy
                  cd book
                  /tmp/deploy
